#!/bin/bash
usage(){
    echo "Usage: $0 [-move] <unsigned.zip|apk|jar>" 
}
if [ $# -lt "1" ]; then
  usage
  exit 1
fi

jarpath=/opt/android-sdk/sign/testsign.jar
javaopts='-Xmx256m'
if [ ! -r $jarpath ]; then
  echo "$0: can't find $jarpath !"
fi

move=""
if [[ $1 = '-move' ]]; then
  move="move"
  shift
fi

while (( $# )); do
  ext=`echo $1 |awk -F . '{ print $NF }'|grep "zip\|jar\|apk"`
  if [ x$ext != x ];then
    echo $1
    fn=`echo $1|sed -e "s:.$ext$::"`
    java $javaopts -classpath $jarpath testsign $1 $fn-signed.$ext 
    if [[ x$move != x ]]; then
      mv $fn-signed.$ext $1
    fi
  fi
  shift
done
echo "All done!"
